#DB Config
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lab_rat}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Flyway Config
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

#Api token
api.security.token.secret=${JWT_SECRET:dev-local-secret-change-me-please}
logging.level.org.springframework.security=DEBUG

#Desativa o retorno do tracktrace nas exceptions
server.error.include-stacktrace=never

#Spring config
logging.level.org.springframework.boot.autoconfigure=OFF

#AI Config
ai.openrouter.api-url=https://openrouter.ai/api/v1/chat/completions
ai.openrouter.api-key=${OPENROUTER_API_KEY:}
elevenlabs.api-key=${ELEVENLABS_API_KEY:}
elevenlabs.voice-id=${ELEVENLABS_VOICE_ID:}
